#ifndef __MGF_COLOR_CONTEXT__
#define __MGF_COLOR_CONTEXT__

#define COLOR_MINIMUM_WAVE_LENGTH 380
#define COLOR_MAXIMUM_WAVE_LENGTH 780
#define COLOR_WAVE_LENGTH_DELTA_I ((float)(COLOR_MAXIMUM_WAVE_LENGTH - COLOR_MINIMUM_WAVE_LENGTH) / (float)(NUMBER_OF_SPECTRAL_SAMPLES - 1))
#define COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE 10000
#define COLOR_PEAK_LUMENS_PER_WATT (683.0/COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE)
#define COLOR_SPECTRUM_IS_SET_FLAG 01
#define COLOR_DEFINED_WITH_SPECTRUM_FLAG 02
#define COLOR_XY_IS_SET_FLAG 04
#define COLOR_DEFINED_WITH_XY_FLAG 010
#define COLOR_EFFICACY_FLAG 020

#define DEFAULT_COLOR_CONTEXT { \
    1, \
    COLOR_DEFINED_WITH_XY_FLAG | COLOR_XY_IS_SET_FLAG | COLOR_SPECTRUM_IS_SET_FLAG | COLOR_EFFICACY_FLAG, \
    { \
        COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, \
        COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, \
        COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, \
        COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, \
        COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, \
        COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, \
        COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE, COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE \
    }, \
    (long)NUMBER_OF_SPECTRAL_SAMPLES * COLOR_NOMINAL_MAXIMUM_SAMPLE_VALUE,                                \
    1.0 / 3.0, \
    1.0 / 3.0, \
    178.006 \
}

#define NUMBER_OF_SPECTRAL_SAMPLES 41 // Number of spectral samples

class MgfColorContext {
  public:
    int clock; // Incremented each change
    short flags; // What's been set
    short straightSamples[NUMBER_OF_SPECTRAL_SAMPLES]; // Spectral samples, min wl to max
    long spectralStraightSum; // Straight sum of spectral values
    float cx; // Chromaticity X value
    float cy; // Chromaticity Y value
    float eff; // Efficacy (lumens / watt)
};

extern void mgfContextFixColorRepresentation(MgfColorContext *clr, int fl);

#endif
