#ifndef RPK_VERTEX_COMPARE_FLAGS_H
#define RPK_VERTEX_COMPARE_FLAGS_H

enum VertexCompareFlags : unsigned {
    VERTEX_COMPARE_LOCATION = 0x01U,
    VERTEX_COMPARE_NORMAL = 0x02U,
    VERTEX_COMPARE_TEXTURE_COORDINATE = 0x04U
};

#endif
