#ifndef __RADIOSITY_RETURN_OPTION__
#define __RADIOSITY_RETURN_OPTION__

enum RadiosityReturnOption {
    GLOBAL_DENSITY,
    CAUSTIC_DENSITY,
    REC_C_DENSITY,
    REC_G_DENSITY,
    IMPORTANCE_C_DENSITY,
    IMPORTANCE_G_DENSITY,
    GLOBAL_RADIANCE,
    CAUSTIC_RADIANCE
};

#endif
