#ifndef STOCHASTIC_RAYTRACING_METHOD__
#define STOCHASTIC_RAYTRACING_METHOD__

enum StochasticRaytracingMethod {
    STOCHASTIC_RELAXATION_RADIOSITY_METHOD,
    RANDOM_WALK_RADIOSITY_METHOD
};

#endif
