plugins {
    id "application"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://jogamp.org/deployment/maven")
    }
}

application {
    mainClass = "vsdk.toolkit.app.Main"
}

dependencies {
    implementation("org.jogamp.jogl:jogl-all:2.5.0")
    implementation("org.jogamp.gluegen:gluegen-rt:2.5.0")
    runtimeOnly("org.jogamp.jogl:jogl-all-main:2.5.0")
    runtimeOnly("org.jogamp.gluegen:gluegen-rt-main:2.5.0")
}

sourceSets {
    joglDemo {
        java {
            srcDirs = ["src/test"]
        }
    }
}

configurations {
    joglDemoImplementation.extendsFrom implementation
    joglDemoRuntimeOnly.extendsFrom runtimeOnly
}

tasks.register("runHelloWorldJOGL", JavaExec) {
    group = "application"
    description = "Run JOGL demo from CLI"
    mainClass = "jogl.HelloWorldJOGL"
    classpath = sourceSets.joglDemo.runtimeClasspath
}

tasks.named("compileJava", JavaCompile) {
    destinationDirectory = layout.buildDirectory.dir("classes/java/main")
}

tasks.named("compileJoglDemoJava", JavaCompile) {
    destinationDirectory = layout.buildDirectory.dir("classes/java/joglDemo")
}

tasks.register("cleanSrcClassFiles", Delete) {
    delete fileTree(dir: "src", include: "**/*.class")
}

tasks.named("build") {
    dependsOn("cleanSrcClassFiles")
}
