#ifndef __MGF_HANDLER_TYPE__
#define __MGF_HANDLER_TYPE__

enum class HandlerRoleContext {
    DISCARD_UNNEEDED,
    INCLUDE_FILE,
    ENTITY_SPHERE,
    ENTITY_TORUS,
    ENTITY_CYLINDER,
    ENTITY_RING,
    ENTITY_CONE,
    ENTITY_PRISM,
    ENTITY_FACE_WITH_HOLES,
    COLOR_SPEC_HELPER,
    COLOR_MIX_HELPER,
    COLOR_TEMPERATURE_HELPER,
    HANDLE_VERTEX,
    HANDLE_FACE,
    HANDLE_FACE_WITH_HOLES,
    HANDLE_SURFACE,
    HANDLE_COLOR,
    HANDLE_MATERIAL,
    HANDLE_TRANSFORM,
    HANDLE_OBJECT
};

#endif
